[package]
name = "brioche-packer"
version = "0.1.0"
edition = "2021"

[dependencies]
brioche-autopack = { path = "../brioche-autopack" }
brioche-pack = { workspace = true }
brioche-resources = { path = "../brioche-resources" }
bstr = "1.9.1"
clap = { version = "4.4.11", features = ["derive"] }
color-eyre = "0.6.3"
eyre = "0.6.12"
globset = "0.4.14"
goblin = "0.8.2"
runnable-core = { path = "../runnable-core" }
schemars = "0.8.21"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.108" }
serde_with = { version = "3.8.1", features = ["schemars_0_8"] }
walkdir = "2.5.0"
