[package]
name = "brioche-packed-plain-exec"
version = "0.1.1"
edition.workspace = true

[dependencies]
brioche-pack = { workspace = true }
brioche-resources = { path = "../brioche-resources" }
bstr = "1.8.0"
libc = "0.2.151"
runnable-core = { path = "../runnable-core" }
serde_json = "1.0.117"
thiserror = "1.0.51"

[lints]
workspace = true
